name: Deploy

on:
  push:
    branches: [main]

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: docker build -t app .

      - run: docker run app bun run lint
      - run: docker run app bun run check
      - run: docker run app bun run test:unit
      - run: docker run app bun run build

      - name: Deploy
        run: |
          docker run \
            -e CLOUDFLARE_API_TOKEN \
            -e CLOUDFLARE_ACCOUNT_ID \
            app bunx wrangler pages deploy .svelte-kit/cloudflare \
            --project-name memory \
            --branch main

      - name: Run D1 migrations
        run: |
          docker run \
            -e CLOUDFLARE_API_TOKEN \
            -e CLOUDFLARE_ACCOUNT_ID \
            app bunx wrangler d1 migrations apply DB
